// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0oW5c-8dJ0G3NNF8uKLFRDcQV6XoSGw',
    appId: '1:833604486285:web:975b84acf613944ca8cec4',
    messagingSenderId: '833604486285',
    projectId: 'taskit-7aa86',
    authDomain: 'taskit-7aa86.firebaseapp.com',
    storageBucket: 'taskit-7aa86.appspot.com',
    measurementId: 'G-R6G3RT8KTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ067BCWw1zaCPqDltEpKOd08Gw43nOpA',
    appId: '1:833604486285:android:6678d90690231d62a8cec4',
    messagingSenderId: '833604486285',
    projectId: 'taskit-7aa86',
    storageBucket: 'taskit-7aa86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxrWDp-aQ3Y4t8KQWRzVSRayLPyws0t3M',
    appId: '1:833604486285:ios:a2598cee820dcf3da8cec4',
    messagingSenderId: '833604486285',
    projectId: 'taskit-7aa86',
    storageBucket: 'taskit-7aa86.appspot.com',
    iosBundleId: 'com.example.taskit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxrWDp-aQ3Y4t8KQWRzVSRayLPyws0t3M',
    appId: '1:833604486285:ios:2fd3ea292d681f04a8cec4',
    messagingSenderId: '833604486285',
    projectId: 'taskit-7aa86',
    storageBucket: 'taskit-7aa86.appspot.com',
    iosBundleId: 'com.example.taskit.RunnerTests',
  );
}
